export const columnWidths = [
    ['Narrow', '30rem'],
    ['Default', '50rem'],
    ['Wide', '70rem'],
    ['Full size', '100vw']]

export const bundleFontList: [string, string][] = [
    ['Open Dyslexic Dense', 'OpenDyslexic|letter-spacing: -0.2rem;'],
    ['Open Dyslexic', 'OpenDyslexic'],
    ['Comfortaa', 'Comfortaa'],
    ['Noto Serif', 'Noto Serif'],
    ['STIX Two', 'STIX Two'],
    ['Roboto Condensed', 'Roboto']]

export const knownFontNames = [
    'Academy Engraved LET',
    'Adwaita Mono',
    'Adwaita Sans',
    'Aharoni',
    'Al Nile',
    'Aldhabi',
    'American Typewriter',
    'Andale Mono',
    'Andalus',
    'Angsana New',
    'AngsanaUPC',
    'Aparajita',
    'Apple Chancery',
    'Apple Color Emoji',
    'AppleGothic',
    'AppleMyungjo',
    'Arabic Typesetting',
    'Archivo',
    'Arial',
    'Arial Black',
    'Arial Hebrew',
    'Arial Narrow',
    'Arvo',
    'Athelas',
    'Avenir',
    'Avenir Next',
    'Avenir Next Condensed',
    'Bahnschrift',
    'Bahnschrift Condensed',
    'Bahnschrift Light',
    'Bahnschrift SemiBold',
    'Barlow',
    'Barlow Condensed',
    'Baskerville',
    'Batang',
    'BatangChe',
    'Big Caslon',
    'Bitter',
    'BIZ UDGothic',
    'BIZ UDMincho',
    'BIZ UDPGothic',
    'BIZ UDPMincho',
    'Bodoni 72',
    'Bodoni 72 Oldstyle',
    'Bodoni 72 Smallcaps',
    'Book Antiqua',
    'Bradley Hand',
    'Browallia New',
    'BrowalliaUPC',
    'Brush Script MT',
    'Cabin',
    'Calibri',
    'Calisto MT',
    'Cambria',
    'Cambria Math',
    'Candara',
    'Cantarell',
    'Cardo',
    'Carrois Gothic SC',
    'Cascadia',
    'Cascadia Code',
    'Cascadia Mono',
    'Century Gothic',
    'Chalkboard',
    'Chalkboard SE',
    'Chalkduster',
    'Charter',
    'Cochin',
    'Comfortaa',
    'Comic Sans MS',
    'Coming Soon',
    'Consolas',
    'Constantia',
    'Copperplate',
    'Copperplate Gothic',
    'Corbel',
    'Cordia New',
    'Courier',
    'Courier New',
    'Crimson Text',
    'Cutive Mono',
    'Dancing Script',
    'DaunPenh',
    'David',
    'DejaVu Sans',
    'DejaVu Sans Mono',
    'DejaVu Serif',
    'DengXian',
    'Didot',
    'DilleniaUPC',
    'DM Sans',
    'DM Serif Display',
    'Droid Sans',
    'Droid Sans Mono',
    'Droid Serif',
    'Dyslexie',
    'EB Garamond',
    'Ebrima',
    'Euphemia UCAS',
    'Exo 2',
    'Fira Mono',
    'Fira Sans',
    'Franklin Gothic Medium',
    'Free Mono',
    'Free Sans',
    'Free Serif',
    'Futura',
    'Gabriola',
    'Gadugi',
    'Geneva',
    'Georgia',
    'Gill Sans',
    'Granjon',
    'Hack',
    'Helvetica',
    'Helvetica Neue',
    'Hoefler Text',
    'Herculanum',
    'IBM Plex Mono',
    'IBM Plex Sans',
    'IBM Plex Serif',
    'Impact',
    'Inconsolata',
    'Ink Free',
    'Inter',
    'Iowan Old Style',
    'JetBrains Mono',
    'Josefin Sans',
    'Josefin Slab',
    'Kailasa',
    'Karla',
    'Lato',
    'Leelawadee UI',
    'Liberation Mono',
    'Liberation Sans',
    'Liberation Serif',
    'Libre Baskerville',
    'Lora',
    'Lucida Console',
    'Lucida Grande',
    'Lucida Sans',
    'Lucida Sans Unicode',
    'Marion',
    'Malayalam Sangam MN',
    'Manrope',
    'Marker Felt',
    'Menlo',
    'Merriweather',
    'Microsoft Sans Serif',
    'Monaco',
    'Mongolian Baiti',
    'Montserrat',
    'MS Gothic',
    'MS Mincho',
    'MS PGothic',
    'NSimSun',
    'New York',
    'Nirmala UI',
    'Noteworthy',
    'Noto Color Emoji',
    'Noto Sans',
    'Noto Sans CJK JP',
    'Noto Sans Mono',
    'Noto Serif',
    'Nunito',
    'Open Dyslexic',
    'Open Dyslexic Dense', // We alias OpenDyslexic for a variant with letter-spacing. It's made up
    'Open Sans',
    'Optima',
    'Oswald',
    'Palatino',
    'Palatino Linotype',
    'Papyrus',
    'Party LET',
    'Phosphate',
    'Playfair Display',
    'Poppins',
    'Roboto',
    'Roboto Condensed',
    'Rockwell',
    'San Francisco Pro',
    'Savoye LET',
    'Segoe Print',
    'Segoe Script',
    'Segoe UI',
    'Segoe UI Emoji',
    'Segoe UI Historic',
    'Segoe UI Light',
    'Segoe UI Semibold',
    'Segoe UI Semilight',
    'Segoe UI Variable',
    'Seravek',
    'SF Compact',
    'SF Mono',
    'SF Pro',
    'SF Pro Display',
    'SignPainter',
    'SimHei',
    'SimSun',
    'Sitka Banner',
    'Sitka Display',
    'Sitka Heading',
    'Sitka Small',
    'Sitka Subheading',
    'Sitka Text',
    'Skia',
    'Snell Roundhand',
    'STIX Two',
    'Superclarendon',
    'Sylfaen',
    'Symbol',
    'Tahoma',
    'Times New Roman',
    'Trattatello',
    'Trebuchet MS',
    'Ubuntu',
    'Ubuntu Condensed',
    'Ubuntu Mono',
    'Verdana',
    'Webdings',
    'Wingdings',
    'Zapfino',
]

export const lineSpacings = [
    ['Dense', '1rem'],
    ['Default', '1.2rem'],
    ['More', '1.5rem'],
    ['Double', '2rem'],
    ['Spacious', '3rem']]

export const paragraphMargins = [
    ['Dense', '-0.75rem'],
    ['Half', '-0.5rem'],
    ['Slight Less', '-0.25rem'],
    ['Default', ''],
    ['Slight more', '1.5rem'],
    ['Double', '2rem'],
    ['Over Double', '2.5rem'],
    ['Triple', '3rem']]

export const boldLevels = [
    ['Default', '400'],
    ['', '']
]

export const letterSpacings = [
    ['Dense', '-0.0375rem'],
    ['Reduce', '-0.02rem'],
    ['Default', ''],
    ['Expand', '0.02rem'],
    ['Wide 1', '0.0375rem'],
    ['Wide 2', '0.05rem'],
    ['Wide 3', '0.1rem']]

export const wordSpacings = [
    ['Less', '-0.05rem'],
    ['Default', ''],
    ['Slight', '0.05rem'],
    ['Expand', '0.1rem'],
    ['Lots', '0.3rem'],
    ['Spacious', '0.5rem']]

export const tintBlends = [
    ['Color', 'color'],
    ['Color Burn', 'color-burn'],
    ['Color Dodge', 'color-dodge'],
    ['Difference', 'difference'],
    ['Exclusion', 'exclusion'],
    ['Hard Light', 'hard-light'],
    ['Hue', 'hue'],
    ['Lighten', 'lighten'],
    ['Luminosity', 'luminosity'],
    ['Multiply', 'multiply'],
    ['Overlay', 'overlay'],
    ['Plus Lighter', 'plus-lighter'],
    ['Saturation', 'saturation'],
    ['Screen', 'screen'],
    ['Soft Light', 'soft-light']]