export const columnWidths = [
    ['Narrow', '30rem'],
    ['Default', '50rem'],
    ['Wide', '70rem'],
    ['Full size', '100vw']]

export const bundleFontList: [string, string][] = [
    ['Open Dyslexic Dense', 'OpenDyslexic|letter-spacing: -0.2rem;'],
    ['Open Dyslexic', 'OpenDyslexic'],
    ['Comfortaa', 'Comfortaa'],
    ['Noto Serif', 'Noto Serif'],
    ['STIX Two', 'STIX Two'],
    ['Roboto Condensed', 'Roboto']]

export const knownFontNames = [
    'Academy Engraved LET',
    'Adwaita Mono',
    'Adwaita Sans',
    'Aharoni',
    'Al Nile',
    'Aldhabi',
    'American Typewriter',
    'Andale Mono',
    'Andalus',
    'Angsana New',
    'AngsanaUPC',
    'Apple Color Emoji',
    'AppleGothic',
    'AppleMyungjo',
    'Arabic Typesetting',
    'Arial',
    'Arial Hebrew',
    'Aparajita',
    'Avenir',
    'Avenir Next',
    'Bahnschrift',
    'Baskerville',
    'Batang',
    'BatangChe',
    'BIZ UDGothic',
    'BIZ UDMincho',
    'BIZ UDPGothic',
    'BIZ UDPMincho',
    'Bodoni 72',
    'Book Antiqua',
    'Browallia New',
    'BrowalliaUPC',
    'Calibri',
    'Calisto MT',
    'Cambria',
    'Cambria Math',
    'Candara',
    'Cantarell',
    'Cascadia',
    'Cascadia Code',
    'Century Gothic',
    'Chalkboard',
    'Chalkboard SE',
    'Cochin',
    'Comfortaa',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Copperplate',
    'Copperplate Gothic',
    'Corbel',
    'Cordia New',
    'Courier New',
    'DaunPenh',
    'David',
    'DejaVu Sans',
    'DejaVu Sans Mono',
    'DejaVu Serif',
    'DengXian',
    'Didot',
    'DilleniaUPC',
    'Dyslexie',
    'Ebrima',
    'Euphemia UCAS',
    'Franklin Gothic Medium',
    'Free Mono',
    'Free Sans',
    'Free Serif',
    'Futura',
    'Gabriola',
    'Geneva',
    'Georgia',
    'Gill Sans',
    'Granjon',
    'Hack',
    'Helvetica',
    'Helvetica Neue',
    'Hoefler Text',
    'Impact',
    'Kailasa',
    'Leelawadee UI',
    'Liberation Mono',
    'Liberation Sans',
    'Liberation Serif',
    'Lucida Console',
    'Lucida Grande',
    'MS Gothic',
    'MS Mincho',
    'MS PGothic',
    'Malayalam Sangam MN',
    'Marker Felt',
    'Menlo',
    'Microsoft Sans Serif',
    'Monaco',
    'Mongolian Baiti',
    'NSimSun',
    'New York',
    'Noteworthy',
    'Noto Color Emoji',
    'Noto Sans',
    'Noto Sans CJK JP',
    'Noto Sans Mono',
    'Noto Serif',
    'Open Dyslexic',
    'Open Dyslexic Dense', // We alias OpenDyslexic for a variant with letter-spacing. It's made up
    'Optima',
    'Palatino',
    'Palatino Linotype',
    'Papyrus',
    'Roboto',
    'Roboto Condensed',
    'SF Compact',
    'SF Pro',
    'SF Pro Display',
    'Savoye LET',
    'Segoe Print',
    'Segoe Script',
    'Segoe UI',
    'Segoe UI Emoji',
    'SimHei',
    'SimSun',
    'Snell Roundhand',
    'STIX Two',
    'Sylfaen',
    'Symbol',
    'Tahoma',
    'Times New Roman',
    'Trebuchet MS',
    'Verdana',
    'Webdings',
    'Wingdings',
    'Zapfino',
]

export const lineSpacings = [
    ['Dense', '1rem'],
    ['Default', '1.2rem'],
    ['More', '1.5rem'],
    ['Double', '2rem'],
    ['Spacious', '3rem']]

export const paragraphMargins = [
    ['Dense', '-0.75rem'],
    ['Half', '-0.5rem'],
    ['Slight Less', '-0.25rem'],
    ['Default', ''],
    ['Slight more', '1.5rem'],
    ['Double', '2rem'],
    ['Over Double', '2.5rem'],
    ['Triple', '3rem']]

export const letterSpacings = [
    ['Dense', '-0.0375rem'],
    ['Reduce', '-0.02rem'],
    ['Default', ''],
    ['Expand', '0.02rem'],
    ['Wide 1', '0.0375rem'],
    ['Wide 2', '0.05rem'],
    ['Wide 3', '0.1rem']]

export const wordSpacings = [
    ['Less', '-0.05rem'],
    ['Default', ''],
    ['Slight', '0.05rem'],
    ['Expand', '0.1rem'],
    ['Lots', '0.3rem'],
    ['Spacious', '0.5rem']]

export const tintBlends = [
    ['Color', 'color'],
    ['Color Burn', 'color-burn'],
    ['Color Dodge', 'color-dodge'],
    ['Difference', 'difference'],
    ['Exclusion', 'exclusion'],
    ['Hard Light', 'hard-light'],
    ['Hue', 'hue'],
    ['Lighten', 'lighten'],
    ['Luminosity', 'luminosity'],
    ['Multiply', 'multiply'],
    ['Overlay', 'overlay'],
    ['Plus Lighter', 'plus-lighter'],
    ['Saturation', 'saturation'],
    ['Screen', 'screen'],
    ['Soft Light', 'soft-light']]